name       : sqlcipher
version    : 4.0.0
release    : 4
source     :
    - https://github.com/sqlcipher/sqlcipher/archive/v4.0.0.tar.gz : c8f5fc6d800aae6107bf23900144804db5510c2676c93fbb269e4a0700837d68
license    : BSD-3 Clause
component  : programming
summary    : SQLCipher is an SQLite extension that provides transparent 256-bit AES encryption of database files.
description: |
    SQLCipher is an SQLite extension that provides transparent 256-bit AES encryption of database files.
builddeps  :
    - pkgconfig(openssl)
    - pkgconfig(sqlite3)
    - pkgconfig(tcl)
setup      : |
    %configure --disable-static \
        CFLAGS="$CFLAGS -DSQLITE_HAS_CODEC" LDFLAGS="-lcrypto" \
        --enable-tempstore=yes
build      : |
    %make
install    : |
    %make_install
