name       : sqlcipher
version    : 3.3.1
release    : 1
source     :
    - https://github.com/sqlcipher/sqlcipher/archive/v3.3.1.tar.gz : ce5167b2e4d7eb1514fd5a8dfc115a11c4b85f5fd88be2a9fd35ffbb684365bf
license    : BSD-3 Clause
summary    : SQLCipher is an SQLite extension that provides transparent 256-bit AES encryption of database files.
description: |
    SQLCipher is an SQLite extension that provides transparent 256-bit AES encryption of database files.
builddeps  :
    - pkgconfig(openssl)
    - pkgconfig(sqlite3)
    - pkgconfig(tcl)
setup      : |
    %configure --disable-static \
        CFLAGS="$CFLAGS -DSQLITE_HAS_CODEC" LDFLAGS="-lcrypto" \
        --enable-tempstore=yes
build      : |
    %make
install    : |
    %make_install
