name       : sqlcipher
version    : 3.4.2
release    : 3
source     :
    - https://github.com/sqlcipher/sqlcipher/archive/v3.4.2.tar.gz : 69897a5167f34e8a84c7069f1b283aba88cdfa8ec183165c4a5da2c816cfaadb
license    : BSD-3 Clause
component  : programming
summary    : SQLCipher is an SQLite extension that provides transparent 256-bit AES encryption of database files.
description: |
    SQLCipher is an SQLite extension that provides transparent 256-bit AES encryption of database files.
builddeps  :
    - pkgconfig(openssl)
    - pkgconfig(sqlite3)
    - pkgconfig(tcl)
setup      : |
    %configure --disable-static \
        CFLAGS="$CFLAGS -DSQLITE_HAS_CODEC" LDFLAGS="-lcrypto" \
        --enable-tempstore=yes
build      : |
    %make
install    : |
    %make_install
